### ISSUE TITLE
How to use delibird

### ISSUE THREAD

**Issue by ReggieMiller** [EeroEternal/delibird#4]
I had used  ‘pip install delibird’ command to install delibird-0.0.5.
But，when i use ‘delibird’ .
It seems to be 'ModuleNotFoundError: No module named 'delibird'.
Must I download the source code to insatll or Is there anyting else I can do? 
thx!

**Comment by EeroEternal** [comment]
can you give more information
platform, error message, python version, or more

**Comment by EeroEternal** [comment]
fixed bug at 0.0.6 version @ReggieMiller
